const mockAPI = [{
  score: 0.9024664,
  show: {
    id: 2315, url: 'https://www.tvmaze.com/shows/2315/shark', name: 'Shark', type: 'Scripted', language: 'English', genres: ['Drama', 'Crime', 'Legal'], status: 'Ended', runtime: 60, averageRuntime: 60, premiered: '2006-09-21', officialSite: null, schedule: { time: '22:00', days: ['Tuesday'] }, rating: { average: 7.8 }, weight: 85, network: { id: 2, name: 'CBS', country: { name: 'United States', code: 'US', timezone: 'America/New_York' } }, webChannel: null, dvdCountry: null, externals: { tvrage: 8490, thetvdb: 79388, imdb: 'tt0805666' }, image: { medium: 'https://static.tvmaze.com/uploads/images/medium_portrait/329/823329.jpg', original: 'https://static.tvmaze.com/uploads/images/original_untouched/329/823329.jpg' }, summary: "<p>Sebastian Stark, a charismatic, supremely self-confident defense attorney who, after a shocking outcome in one of his cases and a personal epiphany, brings his cutthroat tactics to the prosecutor's office as the head of the Los Angeles District Attorney's High Profile Crime Unit. A group of young prosecutors are about to have the learning experience of a lifetime because, though Stark is seeking to redeem himself, he has no intention of cooling his underhanded approach to cases just because he's now working for the \"good guys.\"</p>", updated: 1623777462, _links: { self: { href: 'https://api.tvmaze.com/shows/2315' }, previousepisode: { href: 'https://api.tvmaze.com/episodes/183189' } },
  },
}, {
  score: 0.84858143,
  show: {
    id: 21303, url: 'https://www.tvmaze.com/shows/21303/shark', name: 'Shark', type: 'Documentary', language: 'English', genres: ['Nature'], status: 'Ended', runtime: 60, averageRuntime: 60, premiered: '2015-05-07', officialSite: 'http://www.bbc.co.uk/programmes/p02n7s0d', schedule: { time: '21:00', days: ['Thursday'] }, rating: { average: null }, weight: 0, network: { id: 12, name: 'BBC One', country: { name: 'United Kingdom', code: 'GB', timezone: 'Europe/London' } }, webChannel: null, dvdCountry: null, externals: { tvrage: null, thetvdb: 295438, imdb: 'tt4706496' }, image: { medium: 'https://static.tvmaze.com/uploads/images/medium_portrait/75/188732.jpg', original: 'https://static.tvmaze.com/uploads/images/original_untouched/75/188732.jpg' }, summary: '<p>A major wildlife series on the sharks of the world with over thirty species filmed, showing how they hunt, intricate social lives, courtship, growing up and the threats they face.</p>', updated: 1604739251, _links: { self: { href: 'https://api.tvmaze.com/shows/21303' }, previousepisode: { href: 'https://api.tvmaze.com/episodes/933363' } },
  },
}, {
  score: 0.84442735,
  show: {
    id: 2762, url: 'https://www.tvmaze.com/shows/2762/shark', name: 'Shark', type: 'Scripted', language: 'Korean', genres: ['Drama', 'Crime', 'Thriller'], status: 'Ended', runtime: 63, averageRuntime: 63, premiered: '2013-05-27', officialSite: 'http://www.kbs.co.kr/drama/shark/about/staff/index.html#', schedule: { time: '22:00', days: ['Monday', 'Tuesday'] }, rating: { average: null }, weight: 17, network: { id: 128, name: 'KBS2', country: { name: 'Korea, Republic of', code: 'KR', timezone: 'Asia/Seoul' } }, webChannel: null, dvdCountry: null, externals: { tvrage: 48807, thetvdb: 270337, imdb: null }, image: { medium: 'https://static.tvmaze.com/uploads/images/medium_portrait/14/37199.jpg', original: 'https://static.tvmaze.com/uploads/images/original_untouched/14/37199.jpg' }, summary: "<p>Han Yi Soo who wants to gain omnipotent power to take revenge for his family and he finally points his dagger to a lady he loves. Jo Hae Woo learns about Yi Soo's ugly truth about his family but she cannot stop loving him. This story is about agonizing love and tragic life of a man and a woman.</p>", updated: 1573580157, _links: { self: { href: 'https://api.tvmaze.com/shows/2762' }, previousepisode: { href: 'https://api.tvmaze.com/episodes/204081' } },
  },
}, {
  score: 0.82713985,
  show: {
    id: 35805, url: 'https://www.tvmaze.com/shows/35805/shark', name: 'SHARK', type: 'Scripted', language: 'Japanese', genres: ['Drama', 'Music'], status: 'Ended', runtime: 30, averageRuntime: 27, premiered: '2014-01-11', officialSite: 'http://www.ntv.co.jp/shark2/', schedule: { time: '00:50', days: ['Saturday'] }, rating: { average: null }, weight: 0, network: { id: 137, name: 'NTV', country: { name: 'Japan', code: 'JP', timezone: 'Asia/Tokyo' } }, webChannel: null, dvdCountry: null, externals: { tvrage: null, thetvdb: 276942, imdb: null }, image: { medium: 'https://static.tvmaze.com/uploads/images/medium_portrait/151/379087.jpg', original: 'https://static.tvmaze.com/uploads/images/original_untouched/151/379087.jpg' }, summary: '<p>The five-member band SHARK wants to change the world with their music, and dreams of making their major debut. They struggle but take small steps forward on what is certainly not an easy path. Their sights are set even if it might feel hopeless sometimes, but because of their fellow members they will not give up.</p>', updated: 1573327422, _links: { self: { href: 'https://api.tvmaze.com/shows/35805' }, previousepisode: { href: 'https://api.tvmaze.com/episodes/1439962' } },
  },
}, {
  score: 0.69991493,
  show: {
    id: 329, url: 'https://www.tvmaze.com/shows/329/shark-tank', name: 'Shark Tank', type: 'Reality', language: 'English', genres: [], status: 'Running', runtime: 60, averageRuntime: 60, premiered: '2009-08-09', officialSite: 'http://abc.go.com/shows/shark-tank', schedule: { time: '20:00', days: ['Friday'] }, rating: { average: 7.6 }, weight: 92, network: { id: 3, name: 'ABC', country: { name: 'United States', code: 'US', timezone: 'America/New_York' } }, webChannel: null, dvdCountry: null, externals: { tvrage: 22610, thetvdb: 100981, imdb: 'tt1442550' }, image: { medium: 'https://static.tvmaze.com/uploads/images/medium_portrait/280/701966.jpg', original: 'https://static.tvmaze.com/uploads/images/original_untouched/280/701966.jpg' }, summary: "<p>An exciting new reality show that, in these trying economic times, gives budding entrepreneurs a chance to make their dreams come true and become successful - and possibly wealthy - business people. But the entrepreneurs must first try to convince five tough, multi-millionaire tycoons to part with their own hard-earned cash and give them the funding they need to jumpstart their business ideas.</p><p>Enter the Sharks of <b>Shark Tank</b>, who lifted themselves up by their bootstraps to make their own entrepreneurial dreams come true and turned their ideas into empires. The five Sharks of this ruthless panel are real estate mogul Barbara Corcoran, \"infomercial\" industry pioneer Kevin Harrington, technology innovator Robert Herjavec, fashion icon Daymond John and financial expert Kevin O'Leary.</p>", updated: 1627934511, _links: { self: { href: 'https://api.tvmaze.com/shows/329' }, previousepisode: { href: 'https://api.tvmaze.com/episodes/2092754' } },
  },
}, {
  score: 0.69674355,
  show: {
    id: 5853, url: 'https://www.tvmaze.com/shows/5853/shark-week', name: 'Shark Week', type: 'Documentary', language: 'English', genres: ['Nature'], status: 'Running', runtime: 60, averageRuntime: 61, premiered: '1988-07-17', officialSite: 'http://www.discovery.com/tv-shows/shark-week/', schedule: { time: '20:00', days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] }, rating: { average: 7 }, weight: 96, network: { id: 66, name: 'Discovery Channel', country: { name: 'United States', code: 'US', timezone: 'America/New_York' } }, webChannel: null, dvdCountry: null, externals: { tvrage: null, thetvdb: 125051, imdb: 'tt1146333' }, image: { medium: 'https://static.tvmaze.com/uploads/images/medium_portrait/23/58091.jpg', original: 'https://static.tvmaze.com/uploads/images/original_untouched/23/58091.jpg' }, summary: '<p><b>Shark Week</b> is an annual, week-long TV programming block created by Tom Golden at the Discovery Channel, which features shark-based programming. <i>Shark Week</i> originally premiered on July 17, 1988.</p>', updated: 1625457954, _links: { self: { href: 'https://api.tvmaze.com/shows/5853' }, previousepisode: { href: 'https://api.tvmaze.com/episodes/2121291' } },
  },
}, {
  score: 0.6813411,
  show: {
    id: 56357, url: 'https://www.tvmaze.com/shows/56357/shark-academy', name: 'Shark Academy', type: 'Reality', language: 'English', genres: [], status: 'Running', runtime: 60, averageRuntime: 60, premiered: '2021-07-10', officialSite: 'https://press.discovery.com/us/dsc/programs/shark-academy/', schedule: { time: '22:00', days: ['Sunday'] }, rating: { average: null }, weight: 61, network: { id: 66, name: 'Discovery Channel', country: { name: 'United States', code: 'US', timezone: 'America/New_York' } }, webChannel: null, dvdCountry: null, externals: { tvrage: null, thetvdb: 405796, imdb: null }, image: { medium: 'https://static.tvmaze.com/uploads/images/medium_portrait/339/849150.jpg', original: 'https://static.tvmaze.com/uploads/images/original_untouched/339/849150.jpg' }, summary: "<p><b>Shark Academy</b> follows eight men and women on an intense six-week crash course to secure a coveted crew spot on shark scientist Dr. Riley Elliott's next great shark diving expedition. It's an opportunity of a lifetime for these shark enthusiasts with non-traditional backgrounds to leap ahead in the competitive world of shark research, embarking on the adventure of a lifetime in hopes of making their dreams a reality.</p>", updated: 1626434368, _links: { self: { href: 'https://api.tvmaze.com/shows/56357' }, previousepisode: { href: 'https://api.tvmaze.com/episodes/2131903' } },
  },
}, {
  score: 0.6744708,
  show: {
    id: 7455, url: 'https://www.tvmaze.com/shows/7455/shark-tank', name: 'Shark Tank', type: 'Reality', language: 'English', genres: [], status: 'To Be Determined', runtime: 60, averageRuntime: 55, premiered: '2015-02-08', officialSite: 'http://tenplay.com.au/channel-ten/shark-tank', schedule: { time: '20:40', days: ['Tuesday'] }, rating: { average: null }, weight: 73, network: { id: 149, name: 'Network 10', country: { name: 'Australia', code: 'AU', timezone: 'Australia/Sydney' } }, webChannel: null, dvdCountry: null, externals: { tvrage: 47561, thetvdb: 291351, imdb: 'tt4406222' }, image: { medium: 'https://static.tvmaze.com/uploads/images/medium_portrait/27/68582.jpg', original: 'https://static.tvmaze.com/uploads/images/original_untouched/27/68582.jpg' }, summary: "<p><b>Shark Tank</b>, the critically-acclaimed, Emmy award-winning reality show that has helped re-invigorate entrepreneurship in dozens of countries around the world, premieres on TEN in 2015.</p><p>Hosted by Studio 10 anchor Sarah Harris, <i>Shark Tank</i> features five of Australia's most successful business people, all hunting for the next big idea to turn into a profitable venture.</p><p>Entrepreneurs Janine Allis (Boost Juice), Steve Baxter (internet pioneer), Andrew Banks (Talent2), John McGrath (McGrath Estate Agents) and Naomi Simson (RedBalloon) are Australia's \"Sharks\".</p><p>These self-made multi-millionaires judge the business concepts and products pitched by ordinary Australians and then decide whether to invest their own money to help market and mentor each.</p><p>In exchange for equity in their existing business, the aspiring entrepreneurs must convince a Shark their idea is original and the product worth pursuing … but it takes more than passion to hook a Shark.</p><p>Who will have the best business bait, the right line and the smarts to win a likely tug-of-war? And will anyone be mauled in the <i>Shark Tank?</i></p><p>From the inspiring to the completely impractical, viewers will be captivated by the creations of everyday Australians, young and old, who dare to dream big in an effort to change their fortunes.</p><p>Fifty thousand years ago, indigenous Australians blazed the trail for the inventors of today. <i>Shark Tank</i> celebrates the ingenuity and expertise of a brand new breed of innovators in this must-watch series.</p><p><i>Shark Tank</i> is produced for Network Ten by Shine Australia.</p>", updated: 1607495459, _links: { self: { href: 'https://api.tvmaze.com/shows/7455' }, previousepisode: { href: 'https://api.tvmaze.com/episodes/1508279' } },
  },
}, {
  score: 0.6672523,
  show: {
    id: 23895, url: 'https://www.tvmaze.com/shows/23895/shark-wranglers', name: 'Shark Wranglers', type: 'Reality', language: 'English', genres: ['Adventure'], status: 'Ended', runtime: 60, averageRuntime: 60, premiered: '2012-07-01', officialSite: null, schedule: { time: '22:00', days: ['Sunday'] }, rating: { average: null }, weight: 0, network: { id: 53, name: 'History', country: { name: 'United States', code: 'US', timezone: 'America/New_York' } }, webChannel: null, dvdCountry: null, externals: { tvrage: null, thetvdb: 260397, imdb: 'tt2274582' }, image: { medium: 'https://static.tvmaze.com/uploads/images/medium_portrait/90/225887.jpg', original: 'https://static.tvmaze.com/uploads/images/original_untouched/90/225887.jpg' }, summary: "<p>On the far side of the Atlantic Ocean, in some of the world's most treacherous waters, Chris Fischer and his crew of the shark research vessel OCEARCH are on a mission to decode the mystery of one of the planet's most notorious predators: the great white shark. Fischer and the crew risk life and limb to tag and track the great whites, revealing where they feed, breed and prowl.</p>", updated: 1482521352, _links: { self: { href: 'https://api.tvmaze.com/shows/23895' }, previousepisode: { href: 'https://api.tvmaze.com/episodes/1022371' } },
  },
}, {
  score: 0.63399017,
  show: {
    id: 25045, url: 'https://www.tvmaze.com/shows/25045/shark-trackers', name: 'Shark Trackers', type: 'Reality', language: 'English', genres: [], status: 'Running', runtime: 30, averageRuntime: 30, premiered: '2017-02-07', officialSite: 'http://www.travelchannel.com/shows/shark-trackers', schedule: { time: '23:00', days: ['Tuesday'] }, rating: { average: null }, weight: 0, network: { id: 82, name: 'Travel Channel', country: { name: 'United States', code: 'US', timezone: 'America/New_York' } }, webChannel: null, dvdCountry: null, externals: { tvrage: null, thetvdb: null, imdb: null }, image: { medium: 'https://static.tvmaze.com/uploads/images/medium_portrait/96/241599.jpg', original: 'https://static.tvmaze.com/uploads/images/original_untouched/96/241599.jpg' }, summary: "<p>Ocean explorer Chris Fischer, along with a team of fisherman and scientists, including his wife, Melissa, embark on expeditions of a lifetime catching and tracking great white sharks. The world's oceans are being threatened like never before and without action they have an uncertain future. The team is on a mission to not only gain a better understanding of one the world's most misunderstood creatures, but also preserve the oceans for future generations.</p>", updated: 1486330342, _links: { self: { href: 'https://api.tvmaze.com/shows/25045' }, previousepisode: { href: 'https://api.tvmaze.com/episodes/1061755' } },
  },
}];

export default mockAPI;