const mockAPI = [{
  score: 0.8647381,
  show: {
    id: 9709, url: 'https://www.tvmaze.com/shows/9709/godzilla', name: 'Godzilla', type: 'Animation', language: 'English', genres: ['Adventure', 'Children'], status: 'Ended', runtime: 30, averageRuntime: 30, premiered: '1978-09-09', officialSite: null, schedule: { time: '', days: ['Saturday'] }, rating: { average: null }, weight: 0, network: { id: 1, name: 'NBC', country: { name: 'United States', code: 'US', timezone: 'America/New_York' } }, webChannel: null, dvdCountry: null, externals: { tvrage: null, thetvdb: 251812, imdb: 'tt0177814' }, image: { medium: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/84292.jpg', original: 'https://static.tvmaze.com/uploads/images/original_untouched/33/84292.jpg' }, summary: "<p><b>Godzilla</b> is a 30-minute animated series co-produced between Hanna-Barbera Productionsand Toho Ltd. in 1978 and aired on NBC in the United States and TV Tokyo in Japan. The series is an animated adaptation of the Japanese <i>Godzilla</i> movies produced by Toho.</p><p>The series follows the adventures of a team of scientists on the <i>Calico</i>, a hydrofoil research vessel, headed by Captain Carl Majors. The rest of the crew include scientist Dr. Quinn Darien, her nephew Pete, and her research assistant Brock. Also along for the ride is Godzuki, the \"cowardly cousin\" of Godzilla and Pete's best friend, who has a lighthearted role in the show. Godzuki can <i>attempt</i> to fly using the small wings under his arms. Whenever Godzuki tries to breathe fire, he usually just coughs up smoke rings.</p>", updated: 1613250020, _links: { self: { href: 'https://api.tvmaze.com/shows/9709' }, previousepisode: { href: 'https://api.tvmaze.com/episodes/521127' } },
  },
}, {
  score: 0.6036109,
  show: {
    id: 51029, url: 'https://www.tvmaze.com/shows/51029/godzilla-singular-point', name: 'Godzilla Singular Point', type: 'Animation', language: 'Japanese', genres: ['Anime', 'Science-Fiction'], status: 'Running', runtime: 25, averageRuntime: 25, premiered: '2021-03-25', officialSite: 'https://godzilla-sp.jp/', schedule: { time: '', days: ['Thursday'] }, rating: { average: null }, weight: 91, network: null, webChannel: { id: 1, name: 'Netflix', country: null }, dvdCountry: null, externals: { tvrage: null, thetvdb: 389696, imdb: 'tt13229964' }, image: { medium: 'https://static.tvmaze.com/uploads/images/medium_portrait/280/701621.jpg', original: 'https://static.tvmaze.com/uploads/images/original_untouched/280/701621.jpg' }, summary: '<p>Brought together by a mysterious song, a grad student and an engineer lead the fight against an unimaginable force that may spell doom for the world.</p>', updated: 1625939498, _links: { self: { href: 'https://api.tvmaze.com/shows/51029' }, previousepisode: { href: 'https://api.tvmaze.com/episodes/2098608' } },
  },
}, {
  score: 0.5809629,
  show: {
    id: 9708, url: 'https://www.tvmaze.com/shows/9708/godzilla-the-series', name: 'Godzilla: The Series', type: 'Animation', language: 'English', genres: ['Action', 'Crime'], status: 'Ended', runtime: 30, averageRuntime: 30, premiered: '1998-09-12', officialSite: 'http://www.scifijapan.com/articles/2006/03/28/godzilla-the-series/', schedule: { time: '', days: ['Saturday'] }, rating: { average: null }, weight: 0, network: { id: 4, name: 'FOX', country: { name: 'United States', code: 'US', timezone: 'America/New_York' } }, webChannel: null, dvdCountry: null, externals: { tvrage: null, thetvdb: 76061, imdb: 'tt0177443' }, image: { medium: 'https://static.tvmaze.com/uploads/images/medium_portrait/33/84291.jpg', original: 'https://static.tvmaze.com/uploads/images/original_untouched/33/84291.jpg' }, summary: '<p><b>Godzilla: The Series</b> is an American animated television series which originally aired on Fox Kids in the United States. The show premiered on September 12, 1998, and is a direct follow-up to the 1998 American <i>Godzilla</i> film.</p>', updated: 1574895309, _links: { self: { href: 'https://api.tvmaze.com/shows/9708' }, previousepisode: { href: 'https://api.tvmaze.com/episodes/521366' } },
  },
}, {
  score: 0.34116024,
  show: {
    id: 6238, url: 'https://www.tvmaze.com/shows/6238/magilla-gorilla', name: 'Magilla Gorilla', type: 'Animation', language: 'English', genres: ['Comedy', 'Children'], status: 'Ended', runtime: 30, averageRuntime: 30, premiered: '1964-01-14', officialSite: null, schedule: { time: '', days: [] }, rating: { average: 7 }, weight: 0, network: { id: 3, name: 'ABC', country: { name: 'United States', code: 'US', timezone: 'America/New_York' } }, webChannel: null, dvdCountry: null, externals: { tvrage: null, thetvdb: 76209, imdb: 'tt0060004' }, image: { medium: 'https://static.tvmaze.com/uploads/images/medium_portrait/23/59990.jpg', original: 'https://static.tvmaze.com/uploads/images/original_untouched/23/59990.jpg' }, summary: "<p>Magilla Gorilla was a gorilla for sale in Melvin Peebles' pet shop. Being a drain on finances, Magilla's price was marked down considerably, but he was invariably only purchased for a short time. The customers always ended up returning Magilla, forcing Peebles to refund their money.</p>", updated: 1612650698, _links: { self: { href: 'https://api.tvmaze.com/shows/6238' }, previousepisode: { href: 'https://api.tvmaze.com/episodes/371292' } },
  },
}, {
  score: 0.308191,
  show: {
    id: 21920, url: 'https://www.tvmaze.com/shows/21920/mountain-gorilla', name: 'Mountain Gorilla', type: 'Documentary', language: 'English', genres: ['Nature'], status: 'Ended', runtime: 60, averageRuntime: 60, premiered: '2010-08-22', officialSite: 'http://www.bbc.co.uk/programmes/b00rbvz2', schedule: { time: '20:00', days: ['Sunday'] }, rating: { average: null }, weight: 0, network: { id: 37, name: 'BBC Two', country: { name: 'United Kingdom', code: 'GB', timezone: 'Europe/London' } }, webChannel: null, dvdCountry: null, externals: { tvrage: null, thetvdb: 184221, imdb: 'tt2308448' }, image: { medium: 'https://static.tvmaze.com/uploads/images/medium_portrait/79/198150.jpg', original: 'https://static.tvmaze.com/uploads/images/original_untouched/79/198150.jpg' }, summary: '<p><b>Mountain Gorilla</b> is a detailed, insightful portrayal of our endangered relative. Only discovered a century ago, mountain gorillas inhabit a fragile world. A small number of families cling to existence on the forested peaks of isolated volcanoes in three war-torn countries, surrounded on all sides by a growing human population. Using exclusive access and the latest technology, this extraordinary trilogy seeks to understand more about the lives, the history and the uncertain future of this charismatic species. Alongside captivating footage of the gorillas themselves, we meet the dedicated teams of vets, rangers, researchers and conservationists that all work together to raise awareness of this unique species – but their dedicated work will only succeed with the support of all those who share the land with them.</p>', updated: 1504502470, _links: { self: { href: 'https://api.tvmaze.com/shows/21920' }, previousepisode: { href: 'https://api.tvmaze.com/episodes/957490' } },
  },
}, {
  score: 0.29513353,
  show: {
    id: 40011, url: 'https://www.tvmaze.com/shows/40011/gorilla-and-the-bird', name: 'Gorilla and the Bird', type: 'Scripted', language: 'English', genres: [], status: 'In Development', runtime: null, averageRuntime: null, premiered: null, officialSite: null, schedule: { time: '', days: [] }, rating: { average: null }, weight: 87, network: { id: 8, name: 'HBO', country: { name: 'United States', code: 'US', timezone: 'America/New_York' } }, webChannel: null, dvdCountry: null, externals: { tvrage: null, thetvdb: 390632, imdb: 'tt7456788' }, image: null, summary: "<p><strong>Gorilla and the Bird</strong> is described as an inspirational tale of a\n mother's unconditional love for her bipolar son. It follows Zack (the \nGorilla) as he fights to regain his sanity after a devastating psychotic\n break, turning to the only person who didn't give up on him – his \nmother (The Bird). Once a highly successful public defender for The \nLegal Aid Society of New York, Zach's sudden illness takes him on a \nharrowing journey of delusions and antisocial behavior, leading to his \neventual arrest and commitment to Bellevue Hospital.</p>", updated: 1623564330, _links: { self: { href: 'https://api.tvmaze.com/shows/40011' } },
  },
}, {
  score: 0.2730538,
  show: {
    id: 21840, url: 'https://www.tvmaze.com/shows/21840/mountain-gorilla-mission-critical', name: 'Mountain Gorilla: Mission Critical', type: 'Documentary', language: 'English', genres: ['Nature'], status: 'Ended', runtime: 60, averageRuntime: 60, premiered: '2016-10-09', officialSite: 'http://channel.nationalgeographic.com/wild/mission-critical/galleries/mountain-gorilla/at/home-of-the-gorillas-2110244/', schedule: { time: '21:00', days: ['Sunday'] }, rating: { average: null }, weight: 0, network: { id: 83, name: 'National Geographic WILD', country: { name: 'United States', code: 'US', timezone: 'America/New_York' } }, webChannel: null, dvdCountry: null, externals: { tvrage: null, thetvdb: null, imdb: null }, image: { medium: 'https://static.tvmaze.com/uploads/images/medium_portrait/78/196831.jpg', original: 'https://static.tvmaze.com/uploads/images/original_untouched/78/196831.jpg' }, summary: "<p>In <i>Mountain Gorilla: Mission Critical</i>, National Geographic follows the world's last mountain gorillas.</p>", updated: 1574725638, _links: { self: { href: 'https://api.tvmaze.com/shows/21840' }, previousepisode: { href: 'https://api.tvmaze.com/episodes/954205' } },
  },
}, {
  score: 0.2682203,
  show: {
    id: 10001, url: 'https://www.tvmaze.com/shows/10001/gorilla-family-me', name: 'Gorilla Family & Me', type: 'Documentary', language: 'English', genres: ['Nature'], status: 'Ended', runtime: 60, averageRuntime: 60, premiered: '2015-12-21', officialSite: 'http://www.bbc.co.uk/programmes/b06ts2dk', schedule: { time: '21:00', days: ['Monday', 'Sunday'] }, rating: { average: null }, weight: 0, network: { id: 37, name: 'BBC Two', country: { name: 'United Kingdom', code: 'GB', timezone: 'Europe/London' } }, webChannel: null, dvdCountry: null, externals: { tvrage: null, thetvdb: 304773, imdb: 'tt5467498' }, image: { medium: 'https://static.tvmaze.com/uploads/images/medium_portrait/38/96539.jpg', original: 'https://static.tvmaze.com/uploads/images/original_untouched/38/96539.jpg' }, summary: "<p>Gordon Buchanan travels to the Democratic Republic of Congo to meet a family of rare Grauer's gorillas.</p>", updated: 1608755538, _links: { self: { href: 'https://api.tvmaze.com/shows/10001' }, previousepisode: { href: 'https://api.tvmaze.com/episodes/528413' } },
  },
}];

export default mockAPI;